#!/usr/bin/env bash
#
# setup.sh — provision the whole demo on a fresh Cloudflare account, end to end.
#
# It is idempotent: safe to re-run. It creates the queues, builds + deploys the five
# workers, sets every runtime secret (generating the random ones the first time and
# reusing them after), runs the database migrations, and seeds the demo users.
#
# Prerequisites:
#   • pnpm install      (deps present)
#   • wrangler auth     (run `pnpm exec wrangler login`, or export CLOUDFLARE_API_TOKEN
#                        + CLOUDFLARE_ACCOUNT_ID for a CI/non-interactive run)
#   • a Neon Postgres connection string
#
# Usage:
#   NEON_DATABASE_URL="postgres://…" ./scripts/setup.sh
#
# Optional overrides (otherwise generated + saved to .deploy-secrets.env):
#   ADMIN_TOKEN, BETTER_AUTH_SECRET, INTERNAL_TOKEN
#
set -euo pipefail
cd "$(dirname "$0")/.."

SECRETS_FILE=".deploy-secrets.env"
QUEUES=(trade-migration harvest-tap)
# Workers that serve a built Vite app (need `pnpm --filter <pkg> build` before deploy).
WEB_WORKERS=(keystone helix ui)
# Deploy order — business systems first so the ui's service bindings resolve.
WORKERS=(keystone helix integration hacker ui)

say()  { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m  ! %s\033[0m\n' "$*"; }
gen()  { node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))"; }
wrangler() { pnpm exec wrangler "$@"; }

# --- 0. preflight ------------------------------------------------------------
say "Preflight"
: "${NEON_DATABASE_URL:?Set NEON_DATABASE_URL to your Neon Postgres connection string}"
wrangler whoami >/dev/null || { echo "wrangler not authenticated — run 'pnpm exec wrangler login'"; exit 1; }
echo "  Cloudflare account OK"

# --- 1. secrets (generate once, reuse on re-runs) ----------------------------
say "Secrets"
[ -f "$SECRETS_FILE" ] && { set -a; . "$SECRETS_FILE"; set +a; }
ADMIN_TOKEN="${ADMIN_TOKEN:-$(gen)}"
BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET:-$(gen)}"
INTERNAL_TOKEN="${INTERNAL_TOKEN:-$(gen)}"
cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/setup.sh — gitignored. Keep these to re-run against the same account.
NEON_DATABASE_URL=$NEON_DATABASE_URL
ADMIN_TOKEN=$ADMIN_TOKEN
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
INTERNAL_TOKEN=$INTERNAL_TOKEN
EOF
echo "  Wrote $SECRETS_FILE (ADMIN_TOKEN / BETTER_AUTH_SECRET / INTERNAL_TOKEN)"

# --- 2. queues (idempotent) --------------------------------------------------
say "Queues"
for q in "${QUEUES[@]}"; do
  if wrangler queues create "$q" 2>&1 | grep -qiE 'created|already'; then
    echo "  $q ready"
  else
    warn "queue '$q' may already exist — continuing"
  fi
done

# --- 3. build the Vite apps --------------------------------------------------
say "Building web apps"
for w in "${WEB_WORKERS[@]}"; do
  pnpm --filter "@qstd/${w}-web" build >/dev/null
  echo "  ${w}-web built"
done

# --- 4. deploy workers, capturing each origin --------------------------------
say "Deploying workers"
declare -A URL
for w in "${WORKERS[@]}"; do
  out="$(cd "workers/$w" && wrangler deploy 2>&1)" || { echo "$out"; exit 1; }
  URL[$w]="$(printf '%s' "$out" | grep -oE 'https://[a-z0-9.-]+\.workers\.dev' | head -1)"
  echo "  qstd-$w → ${URL[$w]:-(no workers.dev URL — custom domain?)}"
done

# --- 5. runtime secrets per worker -------------------------------------------
say "Setting runtime secrets"
put() { printf '%s' "$2" | wrangler secret put "$1" --name "qstd-$3" >/dev/null && echo "  qstd-$3 ← $1"; }

for w in keystone helix; do
  put NEON_DATABASE_URL "$NEON_DATABASE_URL" "$w"
  put BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET" "$w"
  put BETTER_AUTH_URL "${URL[$w]:-https://qstd-$w.workers.dev}" "$w"
  put INTERNAL_TOKEN "$INTERNAL_TOKEN" "$w"
done
put NEON_DATABASE_URL "$NEON_DATABASE_URL" ui
put ADMIN_TOKEN "$ADMIN_TOKEN" ui
put INTERNAL_TOKEN "$INTERNAL_TOKEN" ui
put NEON_DATABASE_URL "$NEON_DATABASE_URL" integration
put NEON_DATABASE_URL "$NEON_DATABASE_URL" hacker

# --- 6. database migrations --------------------------------------------------
say "Running migrations"
NEON_DATABASE_URL="$NEON_DATABASE_URL" pnpm --filter @qstd/db migrate

# --- 7. seed demo data -------------------------------------------------------
say "Seeding"
NEON_DATABASE_URL="$NEON_DATABASE_URL" pnpm --filter @qstd/db seed || warn "trade seed skipped/failed"
NEON_DATABASE_URL="$NEON_DATABASE_URL" BETTER_AUTH_SECRET="$BETTER_AUTH_SECRET" \
  pnpm --filter @qstd/auth seed

# --- done --------------------------------------------------------------------
say "Done"
echo "  Pitch / admin : ${URL[ui]:-https://qstd-ui.<your-subdomain>.workers.dev}  (admin token in $SECRETS_FILE)"
echo "  Keystone      : ${URL[keystone]:-?}  (login demo@keystone.local / password1234)"
echo "  Helix         : ${URL[helix]:-?}      (login demo@helix.local / password1234)"
echo
echo "  Secrets saved in $SECRETS_FILE (gitignored). Re-run this script anytime — it's idempotent."
